timeoutInS:        500
repository:        git@github.com:ipa320/cob_navigation_tests_results
collisionsTopic:   collisions
cameraTopics:      [ /topCamera/image_raw ]

route:
    - [ 0,    0,    0 ]
    - [ 0.1,  0.1, -1.56]
    - [ 0,    0,    0 ]
